const express = require('express');
const { isAuthenticated, hasRole } = require('../middleware/auth');
const puppeteer = require('puppeteer');

module.exports = function(pool) {
  const router = express.Router();

  // Generate PDF for an approved/published SOP
  router.get('/:id', isAuthenticated, async (req, res) => {
    try {
      const { rows } = await pool.query(`
        SELECT s.*, u1.name as created_by_name, u2.name as approved_by_name
        FROM sop_documents s
        LEFT JOIN users u1 ON s.created_by = u1.id
        LEFT JOIN users u2 ON s.approved_by = u2.id
        WHERE s.id = $1
      `, [req.params.id]);

      if (!rows.length) return res.status(404).json({ error: 'Not found' });
      const sop = rows[0];

      if (!['approved', 'published'].includes(sop.status) && req.user.role !== 'admin') {
        return res.status(403).json({ error: 'PDF only available for approved/published documents' });
      }

      const html = generateHTML(sop);
      const browser = await puppeteer.launch({
        args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
        headless: 'new'
      });
      const page = await browser.newPage();
      await page.setContent(html, { waitUntil: 'networkidle0' });
      const pdf = await page.pdf({
        format: 'A4',
        printBackground: true,
        margin: { top: '20mm', bottom: '20mm', left: '15mm', right: '15mm' }
      });
      await browser.close();

      // Log PDF generation
      await pool.query(
        `INSERT INTO sop_history (sop_id, action, notes, performed_by) VALUES ($1,'pdf_generated',$2,$3)`,
        [req.params.id, `PDF generated by ${req.user.name}`, req.user.id]
      );

      const filename = `${sop.nomor_sop.replace(/\//g, '-')}_v${sop.version}.pdf`;
      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
      res.send(pdf);
    } catch (err) {
      console.error('PDF error:', err);
      res.status(500).json({ error: err.message });
    }
  });

  return router;
};

function generateHTML(sop) {
  const statusColor = { draft: '#94a3b8', review: '#f59e0b', approved: '#3b82f6', published: '#22c55e' };
  const now = new Date().toLocaleDateString('id-ID', { day: '2-digit', month: 'long', year: 'numeric' });

  return `<!DOCTYPE html>
<html lang="id">
<head>
  <meta charset="UTF-8">
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Inter', sans-serif; color: #1e293b; background: white; }
    .header { background: #0f172a; color: white; padding: 24px 32px; display: flex; justify-content: space-between; align-items: center; }
    .header h1 { font-size: 20px; font-weight: 700; letter-spacing: -0.5px; }
    .header .org { font-size: 12px; opacity: 0.6; margin-top: 4px; }
    .badge { background: ${statusColor[sop.status]}; color: white; padding: 4px 12px; border-radius: 20px; font-size: 11px; font-weight: 600; text-transform: uppercase; }
    .meta-box { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 20px 24px; margin: 24px 0; display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }
    .meta-item label { font-size: 10px; font-weight: 600; text-transform: uppercase; color: #94a3b8; letter-spacing: 0.5px; }
    .meta-item p { font-size: 13px; font-weight: 500; color: #1e293b; margin-top: 2px; }
    .content-area { padding: 24px 0; }
    .content-area h2 { font-size: 14px; font-weight: 600; color: #475569; text-transform: uppercase; letter-spacing: 0.5px; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px; margin-bottom: 16px; }
    .content-body { font-size: 13px; line-height: 1.8; color: #334155; white-space: pre-wrap; }
    .footer { border-top: 1px solid #e2e8f0; padding-top: 16px; margin-top: 32px; display: flex; justify-content: space-between; font-size: 11px; color: #94a3b8; }
    .approval-box { border: 1px solid #e2e8f0; border-radius: 8px; padding: 20px; margin: 24px 0; }
    .approval-box h3 { font-size: 12px; font-weight: 600; text-transform: uppercase; color: #64748b; margin-bottom: 12px; }
    .approval-grid { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 16px; }
    .approval-col { text-align: center; }
    .approval-col label { font-size: 10px; color: #94a3b8; display: block; }
    .approval-col .sig-line { border-bottom: 1px solid #cbd5e1; margin: 32px 8px 8px; }
    .approval-col .name { font-size: 12px; font-weight: 500; }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <h1>OneLab – Standard Operating Procedure</h1>
      <div class="org">Dokumen Resmi | Dilarang digandakan tanpa izin</div>
    </div>
    <span class="badge">${sop.status}</span>
  </div>

  <div style="padding: 0 8px;">
    <div class="meta-box">
      <div class="meta-item"><label>Nomor SOP</label><p>${sop.nomor_sop}</p></div>
      <div class="meta-item"><label>Judul</label><p>${sop.judul_sop}</p></div>
      <div class="meta-item"><label>Departemen</label><p>${sop.departemen || '—'}</p></div>
      <div class="meta-item"><label>Versi</label><p>v${sop.version}.0</p></div>
      <div class="meta-item"><label>Dibuat oleh</label><p>${sop.created_by_name || '—'}</p></div>
      <div class="meta-item"><label>Disetujui oleh</label><p>${sop.approved_by_name || '—'}</p></div>
      ${sop.approved_at ? `<div class="meta-item"><label>Tanggal Disetujui</label><p>${new Date(sop.approved_at).toLocaleDateString('id-ID', {day:'2-digit',month:'long',year:'numeric'})}</p></div>` : ''}
      ${sop.published_at ? `<div class="meta-item"><label>Tanggal Publish</label><p>${new Date(sop.published_at).toLocaleDateString('id-ID', {day:'2-digit',month:'long',year:'numeric'})}</p></div>` : ''}
    </div>

    <div class="content-area">
      <h2>Isi / Konten SOP</h2>
      <div class="content-body">${sop.content || 'Lihat dokumen Google Doc: ' + (sop.link_google_doc || '—')}</div>
    </div>

    ${sop.link_google_doc ? `
    <div style="margin: 16px 0; padding: 12px 16px; background: #eff6ff; border-left: 3px solid #3b82f6; border-radius: 4px; font-size: 12px; color: #1d4ed8;">
      📄 Dokumen lengkap tersedia di: ${sop.link_google_doc}
    </div>` : ''}

    <div class="approval-box">
      <h3>Tanda Tangan Persetujuan</h3>
      <div class="approval-grid">
        <div class="approval-col">
          <label>Dibuat</label>
          <div class="sig-line"></div>
          <div class="name">${sop.created_by_name || '___________'}</div>
          <div style="font-size:10px;color:#94a3b8">Editor</div>
        </div>
        <div class="approval-col">
          <label>Diperiksa</label>
          <div class="sig-line"></div>
          <div class="name">___________</div>
          <div style="font-size:10px;color:#94a3b8">Reviewer</div>
        </div>
        <div class="approval-col">
          <label>Disetujui</label>
          <div class="sig-line"></div>
          <div class="name">${sop.approved_by_name || '___________'}</div>
          <div style="font-size:10px;color:#94a3b8">Approver</div>
        </div>
      </div>
    </div>
  </div>

  <div class="footer">
    <span>${sop.nomor_sop} | ${sop.judul_sop}</span>
    <span>Dicetak: ${now} | Halaman 1 dari 1</span>
  </div>
</body>
</html>`;
}
